CREATE TABLE IF NOT EXISTS product_variants(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  district_id BIGINT REFERENCES districts(id) ON DELETE SET NULL,
  pack_size TEXT NOT NULL,
  price BIGINT NOT NULL,
  archived_at TIMESTAMP NULL
);
